sudo: false
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
env:
  - CXX=g++-4.8 CPATH=$TRAVIS_BUILD_DIR/libspotify-12.1.51-Linux-x86_64-release/include LIBRARY_PATH=$TRAVIS_BUILD_DIR/libspotify-12.1.51-Linux-x86_64-release/lib
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libasound2-dev
before_install:
  - wget https://developer.spotify.com/download/libspotify/libspotify-12.1.51-Linux-x86_64-release.tar.gz
  - tar xzf libspotify-12.1.51-Linux-x86_64-release.tar.gz
